### ISSUE TITLE
Allow to configure skipping symbolic links

### ISSUE THREAD

**Issue by rpieciorak** [meltwater/drone-cache#39]
When caching `node_moodules` directory for `node` projects there are many useful links in `node_modules/.bin` directory.

However, I could not find a way to configure `tar` or `gzip` archiver to include symbolic links into the archive file produces by the plugin.

Missing links force you to reinstall packages which kill the idea of the cache.

**Comment by kakkoyun** [comment]
@rpieciorak Thanks for reporting this. I haven't realized it. It's probably better to include symbolic links by default if they are within the directory. I can also add an option to configure it.

**Comment by adrienharnay** [comment]
Hey, ran into this as well, let me know if I can help to tackle this 🙂 cheers

**Comment by kakkoyun** [comment]
@adrienharnay Thanks. I've started working on it, I'll send the PR soon. I could definitely use some help while testing it.

**Comment by adrienharnay** [comment]
With pleasure!

**Comment by kakkoyun** [comment]
I have released these #42 changes, under `dev` label (exact image: `meltwater/drone-cache:dev')
Automated tests look good, I'm trying to find a node project to test it with. Do you mind testing it with your pipelines as well? @adrienharnay @rpieciorak

**Comment by gabrielboliveira** [comment]
@kakkoyun I tried on a private setup but it didn't work. Its still not caching `node_modules/.bin` folder. I tried with `skip_symlinks: false`, `skip_symlinks: true` and without it.

I have a repo that you can use as an example: https://github.com/gabrielboliveira/newtab/blob/drone-ci/.drone.yml. I did not add the cache step on this specific repo because for me it breaks between builds, so it only works on the private setup.

This is a similar config to what we have on our private repo, that should work with the repo above:

<details><summary>Example config</summary>

```yml
kind: pipeline
name: default

steps:
- name: restore-cache
  image: meltwater/drone-cache:dev
  pull: always
  settings:
    backend: 'filesystem'
    restore: true
    cache_key: '{{ .Repo.Name }}_{{ checksum "yarn.lock" }}'
    mount:
      - 'node_modules'
  volumes:
  - name: cache
    path: /tmp/cache

- name: install
  image: node:alpine
  depends_on: [ restore-cache ]
  commands:
  - yarn install

- name: lint
  image: node:alpine
  depends_on: [ install ]
  commands:
  - yarn lint

- name: rebuild-cache
  image: meltwater/drone-cache:dev
  pull: always
  settings:
    backend: 'filesystem'
    rebuild: true
    cache_key: '{{ .Repo.Name }}_{{ checksum "yarn.lock" }}'
    mount:
      - 'node_modules'
  volumes:
  - name: cache
    path: /tmp/cache

volumes:
- name: cache
  host:
    path: /tmp/cache
```
</details>

This is a failing example when symlinks are not cached:

![image](https://user-images.githubusercontent.com/11093090/59372177-4acc9400-8d1d-11e9-924c-d0616ad1c444.png)

This is an example with no cache, that should be the same result if caching `node_modules/.bin` worked:

![image](https://user-images.githubusercontent.com/11093090/59372531-1dccb100-8d1e-11e9-99b7-a171987e17af.png)

Also I think you forgot to update the DOCS to mention the `skip_symlinks` option of drone plugin on our PR.

**Comment by kakkoyun** [comment]
@gabrielboliveira Thanks a lot for then elaborate feedback. I'll look into the issue in depth over the weekend.

**Comment by kakkoyun** [comment]
Alright, I have found some free time and fixed the issues, it works for me (or on my machine, or with my setup, famous last words 🤣). If you could test with your pipelines, I would be glad. And @gabrielboliveira thanks a lot again, your feedback was extremely helpful.

**Comment by captainjapeng** [comment]
I can confirm that it's working now. Thank!

**Comment by gabrielboliveira** [comment]
I can also confirm that it's working great now! Nice work @kakkoyun 🎉
